FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app /app/app

EXPOSE 8501

CMD ["streamlit", "run", "app/home.py", "--server.port=8501"]
